# Generated by vmake version 10.5b

# Define path to each library
LIB_LIB_MODULE/ = lib_module/

# Define path to each design unit
VCOM = vcom
VLOG = vlog
VOPT = vopt
SCCOM = sccom

whole_library : $(LIB_LIB_MODULE/)/_lib.qdb

$(LIB_LIB_MODULE/)/_lib.qdb :

